# Generated by Django 3.1.5 on 2021-01-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210129_1744'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
