# Generated by Django 3.1.5 on 2021-02-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210131_1815'),
        ('leads', '0004_auto_20210130_0633'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile'),
            preserve_default=False,
        ),
    ]
